# Generated by Django 4.0.3 on 2022-03-15 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('latitute', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bin_Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('collection_frequency', models.IntegerField(default=0)),
                ('last_collection', models.DateTimeField()),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bin')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.operation')),
            ],
        ),
    ]
