# Generated by Django 4.0.3 on 2022-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
